server:
  port: 9090

spring:
  application:
    name: service-identity
  security:
    oauth2:
      authorization-server:
        issuer: http://service-identity:9090
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/orionpay_identity
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
