# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server:
  port: 8080

# ===================================================================
# SPRING BOOT APPLICATION CONFIGURATION
# ===================================================================
spring:
  application:
    name: orionpay-authorization-service

  # --- Database Configuration ---
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/orionpay_db
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always

  # --- Security Configuration (Resource Server) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://service-identity:9090
          jwk-set-uri: http://service-identity:9090/oauth2/jwks

  # --- Cache & Redis Configuration ---
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}

  # --- Kafka Configuration ---
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ===================================================================
# RESILIENCE4J CONFIGURATION
# ===================================================================
resilience4j:
  circuitbreaker:
    instances:
      bandeira:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 20
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
  retry:
    instances:
      bandeira:
        max-attempts: 3
        wait-duration: 200ms
  timelimiter:
    instances:
      bandeira:
        timeout-duration: 3s

# ===================================================================
# CUSTOM APPLICATION PROPERTIES
# ===================================================================
orionpay:
  topics:
    payment-authorized: "payments.authorizations"
  outbox:
    scheduler:
      delay: 10000 # 10 seconds
