INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('453903', 'Visa', 'CREDIT', 'CLASSIC', 'Caixa Econômica Federal', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('548123', 'Mastercard', 'CREDIT', 'GOLD', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('377123', 'American Express', 'CREDIT', 'PLATINUM', 'Bradesco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('498401', 'Visa', 'DEBIT', 'ELECTRON', 'Itau Unibanco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('516292', 'Mastercard', 'DEBIT', 'MAESTRO', 'Santander', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('411122', 'Visa', 'CREDIT', 'PLATINUM', 'Example Bank', 'USA');

-- continuação: 50 BINs adicionais (fictícios, apenas para testes)
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('432100', 'Visa', 'CREDIT', 'GOLD', 'Nubank', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('432101', 'Visa', 'DEBIT', 'CLASSIC', 'Banco Inter', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('455500', 'Visa', 'CREDIT', 'WORLD', 'C6 Bank', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('455501', 'Visa', 'CREDIT', 'CLASSIC', 'Neon Pagamentos', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('404200', 'Visa', 'DEBIT', 'STANDARD', 'Sicredi', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('402360', 'Visa', 'CREDIT', 'GOLD', 'Banco Pan', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('410210', 'Visa', 'CREDIT', 'PLATINUM', 'BTG Pactual', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('411999', 'Visa', 'DEBIT', 'ELECTRON', 'Banco Original', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('417000', 'Visa', 'CREDIT', 'STANDARD', 'Banco do Nordeste', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('418500', 'Visa', 'CREDIT', 'GOLD', 'Banco Safra', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('519000', 'Mastercard', 'CREDIT', 'GOLD', 'PagSeguro', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('519001', 'Mastercard', 'DEBIT', 'STANDARD', 'Stone Pagamentos', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('520400', 'Mastercard', 'CREDIT', 'PLATINUM', 'Mercado Pago', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('520401', 'Mastercard', 'CREDIT', 'WORLD', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('522200', 'Mastercard', 'DEBIT', 'MAESTRO', 'Santander', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('523300', 'Mastercard', 'CREDIT', 'STANDARD', 'Itaú Unibanco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('524400', 'Mastercard', 'CREDIT', 'GOLD', 'Bradesco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('525500', 'Mastercard', 'CREDIT', 'PLATINUM', 'Caixa Econômica Federal', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('526600', 'Mastercard', 'DEBIT', 'STANDARD', 'Banco Inter', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('527700', 'Mastercard', 'CREDIT', 'WORLD', 'C6 Bank', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('222300', 'Mastercard', 'CREDIT', 'GOLD', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('222301', 'Mastercard', 'DEBIT', 'STANDARD', 'Banco Pan', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('272000', 'Mastercard', 'CREDIT', 'BLACK', 'BTG Pactual', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('272001', 'Mastercard', 'CREDIT', 'PLATINUM', 'Banco Safra', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('340500', 'American Express', 'CREDIT', 'GOLD', 'Bradesco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('340501', 'American Express', 'CREDIT', 'PLATINUM', 'Itaú Unibanco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('371200', 'American Express', 'CREDIT', 'CENTURION', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('378200', 'American Express', 'CREDIT', 'GOLD', 'Caixa Econômica Federal', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('506700', 'Elo', 'CREDIT', 'CLASSIC', 'Nubank', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('506701', 'Elo', 'CREDIT', 'GOLD', 'Banco Inter', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('506702', 'Elo', 'DEBIT', 'STANDARD', 'Neon Pagamentos', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('509000', 'Elo', 'CREDIT', 'PLATINUM', 'C6 Bank', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('650400', 'Discover', 'CREDIT', 'STANDARD', 'Banco Original', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('650401', 'Discover', 'DEBIT', 'STANDARD', 'Banco do Nordeste', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('601100', 'Discover', 'CREDIT', 'GOLD', 'Bradesco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('601101', 'Discover', 'CREDIT', 'PLATINUM', 'Itaú Unibanco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('622200', 'UnionPay', 'DEBIT', 'CLASSIC', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('622201', 'UnionPay', 'CREDIT', 'STANDARD', 'Santander', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('356600', 'JCB', 'CREDIT', 'STANDARD', 'Banco Safra', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('356601', 'JCB', 'DEBIT', 'CLASSIC', 'Sicredi', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('305500', 'Diners Club', 'CREDIT', 'STANDARD', 'Banco Pan', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('305501', 'Diners Club', 'CREDIT', 'GOLD', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('630400', 'Maestro', 'DEBIT', 'CLASSIC', 'Caixa Econômica Federal', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('630401', 'Maestro', 'DEBIT', 'STANDARD', 'Santander', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('677100', 'Hipercard', 'CREDIT', 'STANDARD', 'Banco do Brasil', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('677101', 'Hipercard', 'CREDIT', 'GOLD', 'Bradesco', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('589200', 'Aura', 'CREDIT', 'STANDARD', 'Banco Original', 'BRA');
INSERT INTO bin_info (bin_range, brand, card_type, card_level, issuing_bank, country_code) VALUES ('589201', 'Aura', 'DEBIT', 'STANDARD', 'Banco Inter', 'BRA');
