apiVersion: v1
kind: Service
metadata:
  name: service-identity
  namespace: orionpay
spec:
  selector:
    app: service-identity
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-identity
  namespace: orionpay
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: service-identity
  template:
    metadata:
      labels:
        app: service-identity
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "waiting for postgres"; sleep 2; done;']
      containers:
        - name: service-identity
          image: service-identity
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASS
            - name: DB_NAME
              value: "orionpay_identity"
            # CORREÇÃO: Usar o nome do serviço interno do K8s
            - name: OAUTH_ISSUER_URI
              value: "http://service-identity:9090"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 20
          # ADICIONE RECURSOS
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"