apiVersion: v1
kind: Service
metadata:
  name: service-capture
  namespace: orionpay
spec:
  selector:
    app: service-capture
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-capture
  namespace: orionpay
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: service-capture
  template:
    metadata:
      labels:
        app: service-capture
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "capture-svc: waiting for postgres"; sleep 2; done;']
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo "capture-svc: waiting for kafka"; sleep 2; done;']
      containers:
        - name: service-capture
          image: service-capture
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASS
            - name: DB_NAME
              value: "orionpay_capture"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            # --- CORREÇÃO DA SONDA (MAIS PACIÊNCIA) ---
            initialDelaySeconds: 90 # Aumentado de 30
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 120 # Aumentado
            periodSeconds: 20