# Arquivo: k8s-manifests/09-service-settlement.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-settlement
  namespace: orionpay
spec:
  selector:
    app: service-settlement
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-settlement
  namespace: orionpay
spec:
  replicas: 1
  progressDeadlineSeconds: 600 # <--- ADICIONE ESTA LINHA
  selector:
    matchLabels:
      app: service-settlement
  template:
    metadata:
      labels:
        app: service-settlement
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo "settlement-svc: waiting for postgres"; sleep 2; done;' ]
        - name: wait-for-kafka
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z kafka-service 9092; do echo "settlement-svc: waiting for kafka"; sleep 2; done;' ]
      containers:
        - name: service-settlement
          image: service-settlement:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASS
            - name: DB_NAME
              value: "orionpay_settlement"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 20