version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - orionpay-network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - orionpay-network

  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_DB: orionpay-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orionpay-network

  service-capture:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-capture
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASS=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://service-identity:9090
    ports:
      - "8082:8082"
    networks:
      - orionpay-network

volumes:
  postgres_data:

networks:
  orionpay-network:
    driver: bridge
